"""bank rec tables

Revision ID: 0b9274ed2046
Revises: 6aaf3a030c4c
Create Date: 2026-04-30 22:45:27.764008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9274ed2046'
down_revision: Union[str, Sequence[str], None] = '6aaf3a030c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('running_balance_cents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cash_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cash_account_id', 'external_id', name='uq_bank_line_external')
    )
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_txn_date'), ['txn_date'], unique=False)

    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('statement_start_balance_cents', sa.Integer(), nullable=False),
    sa.Column('statement_end_balance_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FINALIZED', name='reconciliationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cash_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliations_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliations_period_end'), ['period_end'], unique=False)

    op.create_table('bank_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=False),
    sa.Column('journal_line_id', sa.Integer(), nullable=False),
    sa.Column('bank_statement_line_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['bank_statement_line_id'], ['bank_statement_lines.id'], ),
    sa.ForeignKeyConstraint(['journal_line_id'], ['journal_lines.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_statement_line_id', name='uq_bank_match_bank_line'),
    sa.UniqueConstraint('journal_line_id', name='uq_bank_match_journal_line')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_matches')
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliations_period_end'))
        batch_op.drop_index(batch_op.f('ix_reconciliations_cash_account_id'))

    op.drop_table('reconciliations')
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_txn_date'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_external_id'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_cash_account_id'))

    op.drop_table('bank_statement_lines')
    # ### end Alembic commands ###
