"""period_close

Revision ID: 6bb6d9da51ac
Revises: 0b9274ed2046
Create Date: 2026-04-30 23:02:19.382695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb6d9da51ac'
down_revision: Union[str, Sequence[str], None] = '0b9274ed2046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_closes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('close_through_date', sa.Date(), nullable=False),
    sa.Column('closing_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['closing_journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('close_through_date', name='uq_period_close_date')
    )
    with op.batch_alter_table('period_closes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_closes_close_through_date'), ['close_through_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_closes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_closes_close_through_date'))

    op.drop_table('period_closes')
    # ### end Alembic commands ###
